
services:
  postgres:
    image: postgres
    container_name: bd_postgres
    environment:
      POSTGRES_DB: serversgaming
      POSTGRES_USER: koko 
      POSTGRES_PASSWORD: unacontraseñasegurasabesbien123
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: