# Database Configuration
quarkus.datasource.db-kind=postgresql
quarkus.datasource.username=koko
quarkus.datasource.password=unacontraseñasegurasabesbien123
quarkus.datasource.jdbc.url=jdbc:postgresql://localhost:5432/serversgaming

# Hibernate
quarkus.hibernate-orm.database.generation=update
quarkus.hibernate-orm.log.sql=true

# Dev mode
quarkus.http.port=8080